// Daftar Frame Style untuk Photobooth Tactile Neo-Brutalism
export const FRAME_STYLES = [
  {
    id: 'white',
    name: 'Classic White',
    subtitle: 'Korean Minimalist',
    bgColor: '#FFFFFF',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#FFFFFF',
    badgeBg: '#F1F5F9',
    badgeText: '#0F172A',
    accentColor: '#0EA5E9',
  },
  {
    id: 'black',
    name: 'Onyx Black',
    subtitle: 'Neo-Brutal Dark',
    bgColor: '#0F172A',
    textColor: '#F8FAFC',
    borderColor: '#F8FAFC',
    swatchColor: '#0F172A',
    badgeBg: '#1E293B',
    badgeText: '#F8FAFC',
    accentColor: '#38BDF8',
  },
  {
    id: 'yellow',
    name: 'Retro Yellow',
    subtitle: 'Warm Sunflower',
    bgColor: '#FDE047',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#FDE047',
    badgeBg: '#FEF08A',
    badgeText: '#854D0E',
    accentColor: '#EAB308',
  },
  {
    id: 'pink',
    name: 'Pastel Pink',
    subtitle: 'Sweet Bubblegum',
    bgColor: '#F472B6',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#F472B6',
    badgeBg: '#FCE7F3',
    badgeText: '#9D174D',
    accentColor: '#EC4899',
  },
  {
    id: 'blue',
    name: 'Sky Blue',
    subtitle: 'Electric Cyan',
    bgColor: '#38BDF8',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#38BDF8',
    badgeBg: '#E0F2FE',
    badgeText: '#0369A1',
    accentColor: '#0284C7',
  },
  {
    id: 'sage',
    name: 'Matcha Sage',
    subtitle: 'Calm Earth Tone',
    bgColor: '#86EFAC',
    textColor: '#064E3B',
    borderColor: '#0F172A',
    swatchColor: '#86EFAC',
    badgeBg: '#DCFCE7',
    badgeText: '#15803D',
    accentColor: '#10B981',
  },
  {
    id: 'lilac',
    name: 'Pastel Lilac',
    subtitle: 'Dreamy Violet',
    bgColor: '#C084FC',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#C084FC',
    badgeBg: '#F3E8FF',
    badgeText: '#7E22CE',
    accentColor: '#9333EA',
  },
  {
    id: 'win95',
    name: 'Windows 95',
    subtitle: 'Classic OS 90s',
    bgColor: '#C3C7CB',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#C3C7CB',
    badgeBg: '#E2E8F0',
    badgeText: '#0F172A',
    accentColor: '#008080',
  },
  {
    id: 'gameboy',
    name: 'GameBoy 8-Bit',
    subtitle: 'Retro LCD Green',
    bgColor: '#9BBC0F',
    textColor: '#0F380F',
    borderColor: '#0F380F',
    swatchColor: '#8BAC0F',
    badgeBg: '#D9F99D',
    badgeText: '#0F380F',
    accentColor: '#306230',
  },
  {
    id: 'y2k',
    name: 'Y2K Cyber Acid',
    subtitle: 'Neon Tech Matrix',
    bgColor: '#A3E635',
    textColor: '#022C22',
    borderColor: '#022C22',
    swatchColor: '#A3E635',
    badgeBg: '#ECFCCB',
    badgeText: '#365314',
    accentColor: '#4D7C0F',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave 84',
    subtitle: 'Synthwave Sunset',
    bgColor: '#F43F5E',
    textColor: '#FFFFFF',
    borderColor: '#0F172A',
    swatchColor: '#F43F5E',
    badgeBg: '#FFE4E6',
    badgeText: '#881337',
    accentColor: '#06B6D4',
  },
  {
    id: 'newsprint',
    name: 'Old Newsprint',
    subtitle: 'Vintage Paper Ink',
    bgColor: '#F5EBE0',
    textColor: '#1C1917',
    borderColor: '#1C1917',
    swatchColor: '#F5EBE0',
    badgeBg: '#E7E5E4',
    badgeText: '#1C1917',
    accentColor: '#78716C',
  },
  {
    id: 'film-noir',
    name: '35mm Film Roll',
    subtitle: 'Analogue Negative',
    type: 'film',
    bgColor: '#000000',
    textColor: '#FFFFFF',
    borderColor: '#18181B',
    swatchColor: '#000000',
    badgeBg: '#27272A',
    badgeText: '#FFFFFF',
    accentColor: '#F59E0B',
  },
  {
    id: 'editorial-red',
    name: 'Editorial Red',
    subtitle: 'Studio se.du Bold',
    type: 'editorial',
    bgColor: '#DC2626',
    textColor: '#FFFFFF',
    borderColor: '#0F172A',
    swatchColor: '#DC2626',
    badgeBg: '#FEE2E2',
    badgeText: '#991B1B',
    accentColor: '#FFFFFF',
  },
  {
    id: 'twin-studio',
    name: 'Korean Twin Cut',
    subtitle: 'Twin Strip Duo',
    type: 'twin',
    bgColor: '#F4F4F5',
    textColor: '#0F172A',
    borderColor: '#0F172A',
    swatchColor: '#E4E4E7',
    badgeBg: '#E4E4E7',
    badgeText: '#0F172A',
    accentColor: '#3B82F6',
  },
  {
    id: 'win95-window',
    name: 'Win95 Window',
    subtitle: 'Retro Dialog UI',
    type: 'win95',
    bgColor: '#C0C0C0',
    textColor: '#000000',
    borderColor: '#000000',
    swatchColor: '#008080',
    badgeBg: '#D4D4D8',
    badgeText: '#000000',
    accentColor: '#000080',
  }
];

// Pilihan Layout Photo Strip (Mulai dari 2-wide, 3-vert, hingga 9-asym-film)
export const LAYOUT_OPTIONS = [
  {
    id: '2-wide',
    name: '2-Foto Wide',
    subtitle: 'Duo Strip',
    count: 2,
    cols: 1,
    rows: 2,
    aspect: '1/1',
  },
  {
    id: '3-vert',
    name: '3-Foto Vertikal',
    subtitle: 'Classic 3-Strip',
    count: 3,
    cols: 1,
    rows: 3,
    aspect: '1/1',
  },
  {
    id: '3-cinema',
    name: 'Cinema 3-Cut (16:9)',
    subtitle: 'Widescreen Movie Strip',
    count: 3,
    cols: 1,
    rows: 3,
    aspect: '16/9',
  },
  {
    id: '4-vert',
    name: '4-Foto Vertikal',
    subtitle: 'Classic 4-Cut Strip',
    count: 4,
    cols: 1,
    rows: 4,
    aspect: '4/3',
  },
  {
    id: '4-grid',
    name: '4-Grid Persegi',
    subtitle: '2x2 Quad Strip',
    count: 4,
    cols: 2,
    rows: 2,
    aspect: '1/1',
  },
  {
    id: '5-asym-film',
    name: 'Film Magazine (2+3)',
    subtitle: 'Asymmetric 5-Frame',
    count: 5,
    cols: 2,
    rows: 3,
    type: 'asymmetric',
    aspect: 'dynamic',
  },
  {
    id: '6-double',
    name: '3 x 2 Vertikal',
    subtitle: 'Twin 6-Frame Strip',
    count: 6,
    cols: 2,
    rows: 3,
    aspect: '1/1',
  },
  {
    id: '8-twin',
    name: '4 x 2 Vertikal',
    subtitle: 'Twin 8-Frame Strip',
    count: 8,
    cols: 2,
    rows: 4,
    aspect: '4/3',
  },
  {
    id: '9-asym-film',
    name: 'Film Magazine (4+5)',
    subtitle: 'Asymmetric 9-Frame',
    count: 9,
    cols: 2,
    rows: 5,
    type: 'asymmetric',
    aspect: 'dynamic',
  },
];

// Pilihan Filter Real-Time & Digicam Retro
export const FILTER_OPTIONS = [
  { id: 'none', label: 'Normal', desc: 'Natural Crisp' },
  { id: 'lightleak', label: 'Light Leak 35mm', desc: 'Analog Warm Film Flare' },
  { id: 'filmgrain', label: 'Film Grain 800', desc: 'Retro 35mm Textured Noise' },
  { id: 'lores', label: 'Lo-Res Story', desc: 'Instagram Story Lo-Res' },
  { id: 'goldenhour', label: 'Golden Hour', desc: 'Warm Sunset Glow' },
  { id: 'anime', label: 'Anime Pastel', desc: 'Clean Japanese Film' },
  { id: 'digicam', label: 'Digicam 2000s', desc: 'Canon IXY CCD Sensor' },
  { id: 'cybershot', label: 'Sony Cybershot', desc: 'Cool Tone Y2K CCD' },
  { id: 'fujifilm', label: 'Fuji Chrome', desc: 'Velvia Film Simulation' },
  { id: 'flashpop', label: 'Party Flash', desc: 'Direct Flash Aesthetic' },
  { id: 'camedia', label: 'Olympus Camedia', desc: 'Early 2000s Retro Digi' },
  { id: 'fisheye', label: 'Fisheye Y2K', desc: 'Lensa Cembung Retro' },
  { id: 'softglow', label: 'Soft Dreamy', desc: 'Korean Film Bloom' },
  { id: 'warmfilm', label: 'Kodak Warm', desc: 'Golden 90s Film' },
  { id: 'vintage', label: 'Vintage 90s', desc: 'Low-Res Grain' },
  { id: 'grayscale', label: 'B&W Film', desc: 'Monochrome 90s' },
  { id: 'sepia', label: 'Warm Sepia', desc: 'Golden Nostalgia' },
  { id: 'cyber', label: 'Cyber Neo', desc: 'Futuristic Contrast' },
];

// Pilihan Stiker / Cap Stamp Retro & Aesthetic Lucu
// Stiker pertama/default adalah Kucing, selanjutnya Bebek, setelah itu bebas
export const RETRO_STAMPS = [
  { id: 'none', label: 'Tanpa Stiker', sticker: '', icon: 'none', bgColor: '#FFFFFF', textColor: '#0F172A' },

  // Default: Kucing pertama, Bebek kedua
  { id: 'kitty', label: '🐱 KUCING', sticker: '🐱', icon: 'kitty', bgColor: '#FEF3C7', textColor: '#92400E' },
  { id: 'duck', label: '🦆 BEBEK', sticker: '🦆', icon: 'duck', bgColor: '#FEF9C3', textColor: '#854D0E' },

  // Lucu & Cute Animals
  { id: 'bunny', label: '🐰 KELINCI', sticker: '🐰', icon: 'bunny', bgColor: '#FFE4E6', textColor: '#BE123C' },
  { id: 'bear', label: '🐻 BERUANG', sticker: '🐻', icon: 'bear', bgColor: '#F5EBE0', textColor: '#78350F' },
  { id: 'chick', label: '🐥 CHICK', sticker: '🐥', icon: 'chick', bgColor: '#FEF08A', textColor: '#713F12' },
  { id: 'panda', label: '🐼 PANDA', sticker: '🐼', icon: 'panda', bgColor: '#F1F5F9', textColor: '#0F172A' },
  { id: 'teddy', label: '🧸 BONEKA', sticker: '🧸', icon: 'teddy', bgColor: '#FDE68A', textColor: '#92400E' },
  { id: 'ghost', label: '👻 HANTU', sticker: '👻', icon: 'ghost', bgColor: '#E0E7FF', textColor: '#3730A3' },
  { id: 'cat', label: '🐾 NEKO PAW', sticker: '🐾', icon: 'cat', bgColor: '#F3E8FF', textColor: '#6B21A8' },

  // Makanan & Manis Lucu
  { id: 'strawberry', label: '🍓 STROBERI', sticker: '🍓', icon: 'strawberry', bgColor: '#FFE4E6', textColor: '#E11D48' },
  { id: 'cherry', label: '🍒 CERI', sticker: '🍒', icon: 'cherry', bgColor: '#FFE4E6', textColor: '#BE123C' },
  { id: 'peach', label: '🍑 PERSIK', sticker: '🍑', icon: 'peach', bgColor: '#FFEDD5', textColor: '#C2410C' },
  { id: 'cake', label: '🍰 KUE CAKE', sticker: '🍰', icon: 'cake', bgColor: '#FFF1F2', textColor: '#BE123C' },
  { id: 'boba', label: '🧋 BOBA TEA', sticker: '🧋', icon: 'boba', bgColor: '#FEF3C7', textColor: '#78350F' },
  { id: 'cupcake', label: '🧁 CUPCAKE', sticker: '🧁', icon: 'cupcake', bgColor: '#FCE7F3', textColor: '#9D174D' },
  { id: 'lollipop', label: '🍭 LOLLIPOP', sticker: '🍭', icon: 'lollipop', bgColor: '#FDF2F8', textColor: '#BE185D' },
  { id: 'avocado', label: '🥑 ALPUKAT', sticker: '🥑', icon: 'avocado', bgColor: '#ECFDF5', textColor: '#065F46' },

  // Bunga & Alam Aesthetic
  { id: 'sakura', label: '🌸 SAKURA', sticker: '🌸', icon: 'sakura', bgColor: '#FCE7F3', textColor: '#BE185D' },
  { id: 'tulip', label: '🌷 TULIP', sticker: '🌷', icon: 'tulip', bgColor: '#FFE4E6', textColor: '#BE123C' },
  { id: 'sunflower', label: '🌻 SUNFLOWER', sticker: '🌻', icon: 'sunflower', bgColor: '#FEF08A', textColor: '#854D0E' },
  { id: 'mushroom', label: '🍄 JAMUR', sticker: '🍄', icon: 'mushroom', bgColor: '#FEE2E2', textColor: '#B91C1C' },
  { id: 'lucky', label: '🍀 LUCKY', sticker: '🍀', icon: 'clover', bgColor: '#DCFCE7', textColor: '#15803D' },

  // Coquette, Heart & Y2K Aesthetic
  { id: 'coquette', label: '🎀 PITA', sticker: '🎀', icon: 'ribbon', bgColor: '#FFE4E6', textColor: '#BE123C' },
  { id: 'sparkles', label: '✨ SPARKLE', sticker: '✨', icon: 'sparkles', bgColor: '#FEF9C3', textColor: '#854D0E' },
  { id: 'bubbles', label: '🫧 BUBBLE', sticker: '🫧', icon: 'bubbles', bgColor: '#E0F2FE', textColor: '#0369A1' },
  { id: 'heartbeat', label: '💖 HATI PINK', sticker: '💖', icon: 'heart', bgColor: '#FCE7F3', textColor: '#9D174D' },
  { id: 'love', label: '♡ CINTA', sticker: '♡', icon: 'love', bgColor: '#F472B6', textColor: '#831843' },
  { id: 'crown', label: '👑 MAHKOTA', sticker: '👑', icon: 'crown', bgColor: '#FEF08A', textColor: '#854D0E' },
  { id: 'planet', label: '🪐 SATURNUS', sticker: '🪐', icon: 'planet', bgColor: '#EDE9FE', textColor: '#5B21B6' },
  { id: 'sunglasses', label: '🕶️ COOL', sticker: '🕶️', icon: 'sunglasses', bgColor: '#F1F5F9', textColor: '#0F172A' },
  { id: 'memory', label: '📸 KAMERA', sticker: '📸', icon: 'memory', bgColor: '#C084FC', textColor: '#3B0764' },
  { id: 'smile', label: '☺ SMILE', sticker: '☺', icon: 'smile', bgColor: '#FDE047', textColor: '#0F172A' },
  { id: 'star', label: '✦ Y2K STAR', sticker: '✦', icon: 'star', bgColor: '#F1F5F9', textColor: '#0F172A' },
  { id: 'retro', label: '✧ RETRO', sticker: '✧', icon: 'retro', bgColor: '#38BDF8', textColor: '#0F172A' },
  { id: 'cool', label: '★ BINTANG', sticker: '★', icon: 'cool', bgColor: '#86EFAC', textColor: '#064E3B' },
  { id: 'cyber', label: '⚡ PETIR', sticker: '⚡', icon: 'cyber', bgColor: '#A3E635', textColor: '#022C22' },
  { id: 'pixel', label: '👾 ALIEN', sticker: '👾', icon: 'pixel', bgColor: '#9BBC0F', textColor: '#0F380F' },
  { id: 'cinema', label: '🎟️ TIKET', sticker: '🎟️', icon: 'ticket', bgColor: '#FEF3C7', textColor: '#92400E' },
  { id: 'limited', label: '🏷️ LABEL', sticker: '🏷️', icon: 'limited', bgColor: '#FEF08A', textColor: '#713F12' },
];

// Pola & Tekstur Latar Belakang Frame
export const FRAME_PATTERNS = [
  { id: 'none', label: 'Polos', icon: 'square', desc: 'Warna solid bersih' },
  { id: 'checkerboard', label: 'Papan Catur', icon: 'grid', desc: 'Kotak-kotak retro Y2K' },
  { id: 'polkadot', label: 'Polkadot', icon: 'circle-dot', desc: 'Bintik-bintik manis' },
  { id: 'stripes', label: 'Garis Strip', icon: 'align-justify', desc: 'Garis diagonal retro' },
  { id: 'gridnotebook', label: 'Kertas Kotak', icon: 'layout-grid', desc: 'Grid buku tulis' },
  { id: 'hearts', label: 'Hati', icon: 'heart', desc: 'Pola cinta aesthetic' },
  { id: 'stars', label: 'Bintang', icon: 'star', desc: 'Taburan bintang retro' },
  { id: 'sparkles', label: 'Kilau Y2K', icon: 'sparkles', desc: 'Sparkle aesthetic 2000s' },
  { id: 'clouds', label: 'Awan Pastel', icon: 'cloud', desc: 'Awan manis dreamy' },
  { id: 'halftone', label: 'Halftone Pop', icon: 'disc', desc: 'Titik cetak komik retro' },
  { id: 'filmgrain', label: 'Film Grain', icon: 'film', desc: 'Tekstur analog vintage' },
];

// Pilihan Gaya Font Caption
export const CAPTION_FONTS = [
  { id: 'mono', label: 'Mono Retro', family: "'IBM Plex Mono', monospace", desc: 'Font monospace klasik' },
  { id: 'digital', label: 'LED Digital', family: "'VT323', monospace", desc: 'Jam digital 7-segment' },
  { id: 'typewriter', label: 'Mesin Tik', family: "'Special Elite', cursive", desc: 'Mesin tik jadul' },
  { id: 'cursive', label: 'Tulis Tangan', family: "'Caveat', cursive", desc: 'Tulisan buku harian' },
  { id: 'bubble', label: 'Bubble Y2K', family: "'Fredoka', sans-serif", desc: 'Huruf bulat imut' },
  { id: 'pixel', label: 'Arcade 8-Bit', family: "'Press Start 2P', cursive", desc: 'Game retro pixel' },
  { id: 'serif', label: 'Editorial Serif', family: "'Playfair Display', serif", desc: 'Majalah fashion mewah' },
  { id: 'marker', label: 'Spidol Tebal', family: "'Permanent Marker', cursive", desc: 'Marker graffiti pop-punk' },
  { id: 'korean', label: 'Doodle Imut', family: "'Gaegu', cursive", desc: 'Coretan imut K-Photobooth' },
  { id: 'brutal', label: 'Neo-Brutal', family: "'Rubik Mono One', sans-serif", desc: 'Blok ultra-bold tegas' },
];
